import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App other",
  description: "Generated by create next app",
};

export default function IdLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { userId: string; id: string };
}>) {
  // มี params แต่ไม่มี searchParams ใน layout
  console.log(params, "params in layout userid");

  metadata.title = `Create Next App ${params.userId}`;
  metadata.description = `Generated by create next app ${params.userId}`;

  return (
    <section>
      <div>Id</div>
      <div>{children}</div>
      <div>Id</div>
    </section>
  );
}
